apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: reader-role-test-prom
  namespace: test
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services

  verbs:
  - get
  - list
  - watch
